"""initial schema per-wallet holdings

Revision ID: c53dd174dd58
Revises: 
Create Date: 2026-09-04 16:54:32.030716
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db_types  # tipos personalizados (DecimalText)


# revision identifiers, used by Alembic.
revision: str = 'c53dd174dd58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('coingecko_id', sa.String(), nullable=True),
    sa.Column('binance_symbol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=True)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', app.db_types.DecimalText(), nullable=False),
    sa.Column('total_cost_basis', app.db_types.DecimalText(), nullable=False),
    sa.Column('realized_pnl', app.db_types.DecimalText(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'asset_id', name='uq_holding_wallet_asset')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index('ix_holdings_wallet_asset', ['wallet_id', 'asset_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('open', app.db_types.DecimalText(), nullable=False),
    sa.Column('high', app.db_types.DecimalText(), nullable=False),
    sa.Column('low', app.db_types.DecimalText(), nullable=False),
    sa.Column('close', app.db_types.DecimalText(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timestamp_utc', name='uq_price_asset_ts')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_asset_ts', ['asset_id', 'timestamp_utc'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('quantity', app.db_types.DecimalText(), nullable=False),
    sa.Column('price', app.db_types.DecimalText(), nullable=False),
    sa.Column('fee', app.db_types.DecimalText(), nullable=False),
    sa.Column('fee_currency', sa.String(), nullable=False),
    sa.Column('fee_usdt', app.db_types.DecimalText(), nullable=False),
    sa.Column('date_utc', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_tx_fee_non_negative'),
    sa.CheckConstraint('fee_usdt >= 0', name='ck_tx_fee_usdt_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_tx_quantity_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('ix_transactions_date_utc', ['date_utc'], unique=False)
        batch_op.create_index('ix_transactions_wallet_asset_date', ['wallet_id', 'asset_id', 'date_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_wallet_asset_date')
        batch_op.drop_index('ix_transactions_date_utc')
        batch_op.drop_index('ix_transactions_asset_id')

    op.drop_table('transactions')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_asset_ts')

    op.drop_table('price_history')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index('ix_holdings_wallet_asset')

    op.drop_table('holdings')
    op.drop_table('wallets')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))

    op.drop_table('assets')
    # ### end Alembic commands ###
